export const DEFAULT_STAGE = "Seedling";

export const DEFAULT_TOKEN_OVERRIDES = {
  cardRadius: 24,
  cardBorderAlpha: 0.24,
  cardBorderThickness: 1,
  cardShellPadding: 12,
  cardShadowAlpha: 0.28,
  cardShadowSoftness: 40,
  glassOpacity: 0.58,
  glassBlur: 16,
  typeScale: 1,
  avatarGlowBlur: 2,
  avatarGlowOpacity: 0.65,
  avatarVignetteOpacity: 0.6,
  avatarLensOpacity: 0.16,
  avatarBloomOpacity: 0.25,
  avatarBreathMin: 0.94,
  avatarBreathMax: 1.0,
  avatarBreathDuration: 16,
};

export const PLAYGROUND_PRESETS = {
  default: {
    label: "Default",
    stage: "Seedling",
    tokenOverrides: { ...DEFAULT_TOKEN_OVERRIDES },
  },
  softGlass: {
    label: "Soft Glass",
    stage: "Flame",
    tokenOverrides: {
      ...DEFAULT_TOKEN_OVERRIDES,
      cardRadius: 28,
      cardBorderAlpha: 0.16,
      cardShadowAlpha: 0.2,
      cardShadowSoftness: 56,
      glassOpacity: 0.46,
      glassBlur: 24,
      avatarGlowBlur: 12,
      avatarGlowOpacity: 0.4,
      avatarVignetteOpacity: 0.45,
      avatarLensOpacity: 0.22,
      avatarBloomOpacity: 0.35,
      avatarBreathMin: 0.9,
      avatarBreathMax: 1.04,
      avatarBreathDuration: 20,
    },
  },
  highContrast: {
    label: "High Contrast",
    stage: "Beacon",
    tokenOverrides: {
      ...DEFAULT_TOKEN_OVERRIDES,
      cardRadius: 16,
      cardBorderAlpha: 0.42,
      cardBorderThickness: 2,
      cardShadowAlpha: 0.4,
      cardShadowSoftness: 24,
      glassOpacity: 0.75,
      glassBlur: 8,
      typeScale: 1.08,
      avatarGlowBlur: 4,
      avatarGlowOpacity: 0.75,
      avatarVignetteOpacity: 0.72,
      avatarLensOpacity: 0.12,
      avatarBloomOpacity: 0.18,
      avatarBreathMin: 0.96,
      avatarBreathMax: 1.0,
      avatarBreathDuration: 14,
    },
  },
};

